[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-cloud-storage = "0.8.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
bincode = "1.3.3"
nanorand = "0.7.0"
serde = { version = "1.0.152", features=["derive"] }
serde_json = "1.0.91"
smallvec = { version = "1.10.0", features=["serde"] }
